# Generated by Django 2.1 on 2018-09-25 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Custadv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('cuno', models.CharField(max_length=10, unique=True)),
                ('ipntfy', models.CharField(blank=True, max_length=30)),
                ('ipntfym', models.CharField(blank=True, max_length=30)),
                ('ipntftl', models.CharField(blank=True, max_length=20)),
                ('ipntffx', models.CharField(blank=True, max_length=20)),
                ('ipmnspay', models.BooleanField(blank=True)),
                ('ipentry', models.BooleanField(blank=True)),
                ('iprtord', models.BooleanField(blank=True)),
                ('ipntfmk', models.CharField(blank=True, max_length=30)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custadv_custadv_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, db_column='last_updated_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custadv_custadv_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Custqtn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('org', models.CharField(max_length=3)),
                ('qtndd', models.DateTimeField(blank=True)),
                ('qtns', models.CharField(blank=True, max_length=60)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custadv_custqtn_created_by', to=settings.AUTH_USER_MODEL)),
                ('custadv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custadv.Custadv')),
                ('last_updated_by', models.ForeignKey(blank=True, db_column='last_updated_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custadv_custqtn_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
