# Generated by Django 2.1 on 2018-09-28 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invpars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('midno', models.CharField(max_length=8, unique=True)),
                ('mname', models.CharField(max_length=52)),
                ('taxno', models.CharField(max_length=9)),
                ('seqyy', models.IntegerField(blank=True, default=0, null=True)),
                ('seq01', models.IntegerField(blank=True, default=0, null=True)),
                ('seq02', models.IntegerField(blank=True, default=0, null=True)),
                ('seq03', models.IntegerField(blank=True, default=0, null=True)),
                ('seq04', models.IntegerField(blank=True, default=0, null=True)),
                ('seq05', models.IntegerField(blank=True, default=0, null=True)),
                ('seq06', models.IntegerField(blank=True, default=0, null=True)),
                ('seq07', models.IntegerField(blank=True, default=0, null=True)),
                ('seq08', models.IntegerField(blank=True, default=0, null=True)),
                ('seq09', models.IntegerField(blank=True, default=0, null=True)),
                ('seq10', models.IntegerField(blank=True, default=0, null=True)),
                ('seq11', models.IntegerField(blank=True, default=0, null=True)),
                ('seq12', models.IntegerField(blank=True, default=0, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invpars_invpars_created_by', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, db_column='last_updated_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invpars_invpars_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invstk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('invyymm', models.CharField(max_length=7, unique=True)),
                ('invchar', models.CharField(max_length=2)),
                ('sttno', models.IntegerField(blank=True, default=0, null=True)),
                ('endno', models.IntegerField(blank=True, default=0, null=True)),
                ('nowno', models.IntegerField(blank=True, default=0, null=True)),
                ('usedd', models.DateField(blank=True, null=True)),
                ('boxno', models.CharField(blank=True, max_length=2, null=True)),
                ('machno', models.CharField(blank=True, max_length=1, null=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invpars_invstk_created_by', to=settings.AUTH_USER_MODEL)),
                ('invpars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invpars.Invpars')),
                ('last_updated_by', models.ForeignKey(blank=True, db_column='last_updated_by', editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invpars_invstk_last_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
