# Generated by Django 2.1 on 2018-09-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custcsn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custcsn',
            name='cucgdt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='custcsn',
            name='cucrdt',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='custcsn',
            name='cutrdt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
