# Generated by Django 2.1 on 2018-08-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custadv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuno', models.CharField(max_length=10, unique=True)),
                ('ipntfy', models.CharField(blank=True, max_length=30)),
                ('ipntfym', models.CharField(blank=True, max_length=30)),
                ('ipntftl', models.CharField(blank=True, max_length=20)),
                ('ipntffx', models.CharField(blank=True, max_length=20)),
                ('ipmnspay', models.BooleanField(blank=True)),
                ('ipentry', models.BooleanField(blank=True)),
                ('iprtord', models.BooleanField(blank=True)),
                ('ipntfmk', models.CharField(blank=True, max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Custqtn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org', models.CharField(max_length=3)),
                ('qtndd', models.DateTimeField(blank=True)),
                ('qtns', models.CharField(blank=True, max_length=60)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.IntegerField(default=1)),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.IntegerField(default=1)),
                ('trashed_at', models.DateTimeField(blank=True, null=True)),
                ('custadv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Custadv')),
            ],
        ),
    ]
