# Generated by Django 2.1 on 2018-08-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custqtn',
            name='trashed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custadv',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='custadv',
            name='last_updated_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='custqtn',
            name='created_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='custqtn',
            name='last_updated_by',
            field=models.IntegerField(default=1),
        ),
    ]
